# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: Containerfile.j2
# --------------------------------------------------------------------------

ARG PG_VERSION=14
ARG VECTORCHORD_VERSION=0.5.3

# Builder stage - compile extensions
FROM ghcr.io/daemonless/postgres:${PG_VERSION} AS builder
ARG VECTORCHORD_VERSION

# Build dependencies
RUN pkg update && pkg install -y \
    FreeBSD-bmake FreeBSD-clibs-dev FreeBSD-clang FreeBSD-clang-dev FreeBSD-toolchain \
    FreeBSD-libexecinfo FreeBSD-libexecinfo-dev FreeBSD-runtime-dev FreeBSD-utilities-dev \
    rust gmake git-lite pkgconf \
    && pkg clean -ay

# Build VectorChord from source
RUN fetch -qo /tmp/vectorchord.tar.gz \
    "https://github.com/tensorchord/VectorChord/archive/refs/tags/${VECTORCHORD_VERSION}.tar.gz" && \
    tar -xzf /tmp/vectorchord.tar.gz -C /tmp && \
    cd /tmp/VectorChord-${VECTORCHORD_VERSION} && \
    gmake build && \
    gmake install

# Production image
FROM ghcr.io/daemonless/postgres:${PG_VERSION}

ARG FREEBSD_ARCH=amd64
ARG VECTORCHORD_VERSION
ARG HEALTHCHECK_ENDPOINT="pg_isready -U postgres"

ENV HEALTHCHECK_CMD="${HEALTHCHECK_ENDPOINT}"

# --- Metadata (Injected by Generator) ---
LABEL org.opencontainers.image.title="Immich PostgreSQL" \
      org.opencontainers.image.description="PostgreSQL with pgvector and vectorchord extensions required by Immich for vector similarity search. Defaults to PostgreSQL 14 (:latest), PostgreSQL 18 available as :18." \
      org.opencontainers.image.source="https://github.com/daemonless/immich-postgres" \
      org.opencontainers.image.url="https://immich.app/" \
      org.opencontainers.image.licenses="PostgreSQL" \
      org.opencontainers.image.vendor="daemonless" \
      org.opencontainers.image.authors="daemonless" \
      io.daemonless.category="Databases" \
      io.daemonless.port="5432" \
      io.daemonless.volumes="/var/lib/postgresql/data" \
      io.daemonless.arch="${FREEBSD_ARCH}" \
      io.daemonless.vectorchord-version="${VECTORCHORD_VERSION}" \
      io.daemonless.healthcheck-cmd="${HEALTHCHECK_ENDPOINT}" \
      org.freebsd.jail.allow.sysvipc="required"

# Copy VectorChord extension from builder (pgvector already in base image)
COPY --from=builder /usr/local/lib/postgresql/vchord.so /usr/local/lib/postgresql/
COPY --from=builder /usr/local/share/postgresql/extension/vchord* /usr/local/share/postgresql/extension/

# Fix permissions
RUN chmod 644 /usr/local/share/postgresql/extension/vchord* && \
    chmod 755 /usr/local/lib/postgresql/vchord.so

# Copy init scripts for extensions
COPY docker-entrypoint-initdb.d/ /docker-entrypoint-initdb.d/
RUN chmod 644 /docker-entrypoint-initdb.d/*

# Immich-specific defaults
ENV POSTGRES_DB=immich \
    POSTGRES_SHARED_PRELOAD_LIBRARIES=vchord

# --- Expose (Injected by Generator) ---
EXPOSE 5432

# --- Volumes (Injected by Generator) ---
VOLUME /var/lib/postgresql/data